VFDCSV02 ;DSS/LM - SAVE STATE BACKGROUND TASKS ;6/12/07  09:04
 ;;2011.1.2;DSS,INC VXVISTA OPEN SOURCE;;28 Jan 2013;Build 153
 ;Copyright 1995-2013,Document Storage Systems Inc. All Rights Reserved
 ;
 Q
PURGE ;;Option VFDC INTERPROCESS COM PURGE
 ; Delete obsolete entries, as indicated by PURGE DATE/TIME field value 
 N VFDCDA,VFDCDT,VFDCENDT,VFDCFDA
 S VFDCDT="",VFDCENDT=$$DT^XLFDT
 F  S VFDCDT=$O(^VFD(21651,"F",VFDCDT)) Q:'VFDCDT!(VFDCDT>VFDCENDT)  D
 .S VFDCDA="" F  S VFDCDA=$O(^VFD(21651,"F",VFDCDT,VFDCDA)) Q:'VFDCDA  D
 ..S VFDCFDA(21651,VFDCDA_",",.01)="@"
 ..D FILE^DIE(,"VFDCFDA")
 ..Q
 .Q
 Q
