APCDAPRB ; IHS/CMI/TUCSON - PROMPT FOR PROBLEM ; [ 06/17/02  9:48 AM ]
 ;;2.0;IHS RPMS/PCC Data Entry;**5**;MAR 09, 1999
 ;
START ;
 X:$D(^DD(9000011,.01,12.1)) ^DD(9000011,.01,12.1) S DIC="^ICD9(",DIC(0)="AEMQ",DIC("A")="Enter Problem Diagnosis: " D ^DIC K DIC
 G:Y="" XIT
 I Y=-1,X=""!(X="^") S APCDTSKI=1,APCDLOOK="" G XIT
 I Y=-1 S APCDTERR=1,APCDLOOK="" G XIT
 S APCDLOOK="`"_+Y,APCDTNQP=X
XIT K Y,X,DO,D,DD,DIPGM
 Q
PL ;EP
 I $G(APCDDATE)="" S APCDDATE=DT
 I $G(APCDLOC)="" S APCDLOC=DUZ(2)
 S DFN=APCDPAT,Y=APCDPAT D ^AUPNPAT K Y
 S APCDPLL=APCDLOC,APCDPLD=$P(APCDDATE,".")
 D EN^XBNEW("PL1^APCDAPRB","DFN;APCDPLL;APCDPLD")
 Q
PL1 ;EP
 D ENDE^APCDPL
 Q
PO ;EP
 S DIE="^AUPNPAT(",DR="[APCD PO (ADD)]",DA=APCDPAT D ^DIE K DA,DR,DIE
 Q
MPO ;EP
 S DIE="^AUPNPAT(",DR="[APCD MPO (MPO)]",DA=APCDPAT D ^DIE K DA,DR,DIE
 Q
RPO ;EP
 S DIE="^AUPNPAT(",DR="[APCD RPO (RPO)]",DA=APCDPAT D ^DIE K DA,DR,DIE
 Q
IPO ;EP
 S DIE="^AUPNPAT(",DR="[APCD IPO (IPO)]",DA=APCDPAT D ^DIE K DA,DR,DIE
 Q
APO ;EP
 S DIE="^AUPNPAT(",DR="[APCD APO (APO)]",DA=APCDPAT D ^DIE K DA,DR,DIE
 Q
MNN ;EP
 S DIE="^AUPNPAT(",DR="[APCD MNN (MNN)]",DA=APCDPAT D ^DIE K DA,DR,DIE
 Q
RNO ;EP
 S DIE="^AUPNPAT(",DR="[APCD RNO (RNO)]",DA=APCDPAT D ^DIE K DA,DR,DIE
 Q
PDSP ;EP
 S DIE="^AUPNPAT(",DR="[APCD PDSP (PDSP)]",DA=APCDPAT D ^DIE K DA,DR,DIE
 Q
NON ;EP called from APCD NO (ADD) template
 D ^XBNEW("NO^APCDAPRB:APCD*")
 Q
NOP ;EP called from APCD PO (ADD) template
 D ^XBNEW("NO1^APCDAPRB:APCD*")
 Q
NO ;EP add a note to a problem
 D ^APCDPROB
 K DIR,DIRUT S DIR(0)="F^1:12",DIR("A")="Enter Problem Number" K DA D ^DIR K DIR
 G:$D(DIRUT) NOX
 S APCDPR=Y
 D ^APCDPLK
 I APCDPERR=1 W $C(7),$C(7),"Not a valid problem number.",! K APCDPERR G NO
 ;display existing notes, get next note number
NO1 ;EP
 S APCDPROB=APCDPDFN
 I APCDPROB["`" S APCDPROB=$P(APCDPROB,"`",2)
 I $G(APCDPR)]"" W !!,"Problem Number: ",APCDPR,?40,"Diagnosis: ",$P(^ICD9($P(^AUPNPROB(APCDPROB,0),U),0),U)
 I $O(^AUPNPROB(APCDPROB,11,0)) D
 .W !,"Problem Notes:  " S L=0 F  S L=$O(^AUPNPROB(APCDPROB,11,L)) Q:L'=+L  I $O(^AUPNPROB(APCDPROB,11,L,11,0)) W !?5,$P(^DIC(4,$P(^AUPNPROB(APCDPROB,11,L,0),U),0),U) D
 ..S X=0 F  S X=$O(^AUPNPROB(APCDPROB,11,L,11,X)) Q:X'=+X  W !?10,"Note#",$P(^AUPNPROB(APCDPROB,11,L,11,X,0),U)," ",$$FMTE^XLFDT($P(^(0),U,5),5),?28,$P(^AUPNPROB(APCDPROB,11,L,11,X,0),U,3)
 W ! S DIR(0)="Y",DIR("A")="Add a new Problem Note for this Problem",DIR("B")="N" K DA D ^DIR K DIR
 G:$D(DIRUT) NOX
 G:Y=0 NOX
 ;get next note number
NUM ;
 ;add location multiple if necessary, otherwise get ien in multiple
 S APCDNIEN=$O(^AUPNPROB(APCDPROB,11,"B",APCDLOC,0))
 I APCDNIEN="" S X="`"_APCDLOC,DIC="^AUPNPROB("_APCDPROB_",11,",DA(1)=APCDPROB,DIC(0)="L",DIC("P")=$P(^DD(9000011,1101,0),U,2) D ^DIC K DIC,DA,DR,Y,X S APCDNIEN=$O(^AUPNPROB(APCDPROB,11,"B",APCDLOC,0))
 I APCDNIEN="" W $C(7),$C(7),"ERROR UPDATING NOTE LOCATION MULTIPLE" G NOX
 S (Y,X)=0 F  S Y=$O(^AUPNPROB(APCDPROB,11,APCDNIEN,11,"B",Y)) S:Y X=Y I 'Y S X=X+1 K Y Q
 S APCDNUM=X
 W !!,"Adding ",$P(^DIC(4,APCDLOC,0),U)," Note #",X
 K DIC S X=APCDNUM,DA(1)=APCDNIEN,DA(2)=APCDPROB,DIC="^AUPNPROB("_APCDPROB_",11,"_APCDNIEN_",11,",DIC("P")=$P(^DD(9000011.11,1101,0),U,2),DIC(0)="L" D ^DIC K DA,DR
 I Y=-1 W !!,$C(7),$C(7),"ERROR when updating note number multiple",! G NOX
 S DIE=DIC K DIC W ?10 S %=$S($G(APCDDATE):$P(APCDDATE,"."),1:DT),DA=+Y,DR=".03;.05///^S X=%" D ^DIE K DIE,DR,DA,Y W !!
 S DIE="^AUPNPROB(",DA=APCDPROB,%=$S($G(APCDDATE):$P(APCDDATE,"."),1:DT),DR=".03////"_%_";.14////"_DUZ D ^DIE K DIE,DA,DR,Y
 G NO1
 Q
NOX ;
 K Y,APCDPROB,X,L,APCDNUM,APCDNIEN,DIC,DA,DD
 Q
