VFDVOHXX ;DSS/LM - Post-install routine
 ;;2009.2;DSS,INC VXVISTA OPEN SOURCE;;01 Dec 2009
 ;Copyright 1995-2009,Document Storage Systems Inc. All Rights Reserved
 ; (c) Document Storage Systems, Inc. 2005
 ;
 ; Active integration agreements
 ; 
 ; 2051   $$FIND1^DIC
 ; 2053   UPDATE^DIE
 ; 
 Q
EN ;;Main Entry
 N VFDVACTP,VFDVAIEN,VFDVEXTP,VFDVFDA,VFDVI,VFDVIENS,VFDVX
 F VFDVI=1:1 S VFDVX=$P($T(XP+VFDVI),";",2,3) Q:VFDVX=""  D
 .S VFDVEXTP=$P(VFDVX,";"),VFDVACTP=$P(VFDVX,";",2)
 .S VFDVIENS=$$FIND1^DIC(101,,"X",VFDVEXTP,"B")_"," Q:'VFDVIENS
 .S VFDVAIEN=$$FIND1^DIC(101,,"X",VFDVACTP,"B") Q:'VFDVAIEN
 .S VFDVFDA(101.01,"?+1,"_VFDVIENS,.01)=VFDVAIEN
 .S VFDVFDA(101.01,"?+1,"_VFDVIENS,3)=999 ;Sequence=Last
 .D:$D(VFDVFDA) UPDATE^DIE(,"VFDVFDA") K VFDVFDA
 .Q
 Q
XP ;;Protocols List - ;VistA Extended Action;VFDVOH Action
 ;OR EVSEND DGPM;VFDV RECEIVE DGPM
 ;OR EVSEND FH;VFDV RECEIVE FH
 ;OR EVSEND GMRC;VFDV RECEIVE GMRC
 ;OR EVSEND LRAP;VFDV RECEIVE LRAP
 ;OR EVSEND LRBB;VFDV RECEIVE LRBB
 ;OR EVSEND LRCH;VFDV RECEIVE LRCH
 ;OR EVSEND ORG;VFDV RECEIVE ORG
 ;OR EVSEND PS;VFDV RECEIVE PS
 ;OR EVSEND RA;VFDV RECEIVE RA
 ;
