VFDVXVER ;DSS/LM - vxVistA version - January 11, 2008
 ;;2009.2;DSS,INC VXVISTA OPEN SOURCE;;01 Dec 2009
 ;Copyright 1995-2009,Document Storage Systems Inc. All Rights Reserved
 ;
 Q
VER(VFDRSLT) ;;[RPC] VFD VXVISTA VERSION
 ;
 N DUZ,U S U="^" D DUZ^XUP(.5)
 S VFDRSLT=$$GET1^DIQ(8989.3,1,"207:1")
 S VFDRSLT=VFDRSLT_U_$$GET^XPAR("SYS","VFD VXVISTA VERSION")
 S:$P(VFDRSLT,U,2)>0 VFDRSLT=VFDRSLT_U_+$$GET^XPAR("SYS","VFD AUTH ENABLE")
 Q
